using glTFLoader.Schema;
using System.Collections.Generic;
using System;
using System.IO;
using System.Reflection;
using System.Diagnostics;
using System.Text;

namespace AssetGenerator
{
    class ExtraData: Extras
    {
        public string Attributes { get; set; }
    }
    internal class Program
    {
        private static void Main(string[] args)
        {
            Stopwatch.StartNew();

            var executingAssembly = Assembly.GetExecutingAssembly();
            var executingAssemblyFolder = Path.GetDirectoryName(executingAssembly.Location);
            var imageFolder = Path.Combine(executingAssemblyFolder, "ImageDependencies");

            Tests[] testBatch = new Tests[]
            {
                //Tests.Material,
                Tests.Material_Alpha,
                //Tests.Material_MetallicRoughness,
                //Tests.Texture_Sampler,
                //Tests.Primitive_Attribute
            };

            foreach (var test in testBatch)
            {
                TestValues makeTest = new TestValues(test);
                var combos = makeTest.ParameterCombos();
                var csv = new StringBuilder();
                var md = new StringBuilder();
                List<string> mdLogHeader = new List<string>(); ;
                List<List<string>> mdLogPrereqs = new List<List<string>>();
                List<List<string>> mdLog = new List<List<string>>();
                string lastName = null;

                // Delete any preexisting files in the output directories, then create those directories if needed
                var assetFolder = Path.Combine(executingAssemblyFolder, test.ToString());
                var trashFolder = Path.Combine(executingAssemblyFolder, "Delete");
                bool tryAgain = true;
                while (tryAgain)
                {
                    try
                    {
                        Directory.Move(assetFolder, trashFolder);
                        Directory.Delete(trashFolder, true);
                        tryAgain = false;
                    }
                    catch (DirectoryNotFoundException)
                    {
                        // Do nothing
                        tryAgain = false;
                    }
                    catch (IOException)
                    {
                        Console.WriteLine("Unable to delete the directory.");
                        Console.WriteLine("Verify that there are no open files and that the current user has write permission to that directory.");
                        Console.WriteLine("Press any key to try again.");
                        Console.ReadKey();
                        tryAgain = true;
                    }
                }

                Directory.CreateDirectory(assetFolder);

                // Setup the log file header
                mdLogHeader.Add("The first table contains attributes that are explicitly set in every model generated by this test.  ");
                mdLogHeader.Add("No attributes are explicitly set in every model generated by this test, other than those in the base model.  ");
                mdLogHeader.Add("The second table contains a grid showing which attributes are being set for a given model. ");
                mdLogHeader.Add("All values of Byte and Short are normalized unsigned. ");

                if (makeTest.requiredParameters != null)
                {
                    // List attributes that are set in every generated model (prerequisites)
                    mdLogPrereqs.Add(new List<string>()); // First line of table must be blank
                    mdLogPrereqs.Add(new List<string>
                    {
                    "Attribute", // First cells are a static label
                    "**Values**"
                    });
                    mdLogPrereqs.Add(new List<string>
                    {
                    ":---:", // Hyphens for row after header
                    ":---:",
                    });
                    for (int i = 0; i < makeTest.requiredParameters.Count; i++)
                    {
                        string attributeName;
                        attributeName = makeTest.requiredParameters[i].name.ToString();
                        attributeName = makeTest.GenerateNameWithSpaces(attributeName);
                        mdLogPrereqs.Add(new List<string>
                        {
                        attributeName,
                        makeTest.ConvertValueToString(makeTest.requiredParameters[i])
                        });
                    }
                }

                // Now start the table for generated models
                mdLog.Add(new List<string>()); // First line of table must be blank
                mdLog.Add(new List<string>
                {
                    "Index" // First cell is a static header name
                });
                mdLog.Add(new List<string>
                {
                    ":---:" // Hyphens for row after header 
                });
                for (int i = 0; i < makeTest.parameters.Count; i++)
                {
                    string attributeName;
                    if (makeTest.parameters[i].prerequisite != ParameterName.Undefined && makeTest.parameters[i].binarySet == 0)
                    {
                        attributeName = makeTest.parameters[i].prerequisite.ToString() + makeTest.parameters[i].name.ToString();
                    }
                    else
                    {
                        attributeName =  makeTest.parameters[i].name.ToString();
                    }
                    attributeName = makeTest.GenerateNameWithSpaces(attributeName);
                    if (attributeName != lastName) // Skip duplicate names caused by non-binary attributes
                    {
                        lastName = attributeName;
                        mdLog[1].Add(attributeName);
                        mdLog[2].Add(":---:");
                    }
                }

                int numCombos = combos.Count;
                for (int comboIndex = 0; comboIndex < numCombos; comboIndex++)
                {
                    string[] name = makeTest.GenerateName(combos[comboIndex]);

                    var gltf = new Gltf
                    {
                        Asset = new Asset
                        {
                            Generator = "glTF Asset Generator",
                            Version = "2.0",
                            Extras = new ExtraData
                            {
                                Attributes = String.Join(" - ", name)
                            }
                        }
                    };

                    var dataList = new List<Data>();

                    var geometryData = new Data(test.ToString() + "_" + comboIndex + ".bin");
                    dataList.Add(geometryData);
                    Runtime.GLTF wrapper = Common.SinglePlaneWrapper(gltf, geometryData);
                    Runtime.Material mat = new Runtime.Material();

                    if (makeTest.testArea == Tests.Material)
                    {
                        mat.MetallicRoughnessMaterial = new Runtime.MetallicRoughnessMaterial();

                        foreach (Parameter req in makeTest.requiredParameters)
                        {
                            if (req.name == ParameterName.MetallicFactor)
                            {
                                mat.MetallicRoughnessMaterial.MetallicFactor = req.value;
                            }
                        }

                        foreach (Parameter param in combos[comboIndex])
                        {
                            if (param.name == ParameterName.EmissiveFactor)
                            {
                                mat.EmissiveFactor = param.value;
                            }
                            else if (param.name == ParameterName.NormalTexture)
                            {
                                mat.NormalTexture = new Runtime.Texture();
                                mat.NormalTexture.Source = param.value;
                            }
                            else if (param.name == ParameterName.Scale && param.prerequisite == ParameterName.NormalTexture)
                            {
                                mat.NormalScale = param.value;
                            }
                            else if (param.name == ParameterName.OcclusionTexture)
                            {
                                mat.OcclusionTexture = new Runtime.Texture();
                                mat.OcclusionTexture.Source = param.value;
                            }
                            else if (param.name == ParameterName.Strength && param.prerequisite == ParameterName.OcclusionTexture)
                            {
                                mat.OcclusionStrength = param.value;
                            }
                            else if (param.name == ParameterName.EmissiveTexture)
                            {
                                mat.EmissiveTexture = new Runtime.Texture();
                                mat.EmissiveTexture.Source = param.value;
                            }
                        }
                    }

                    if (makeTest.testArea == Tests.Material_Alpha)
                    {
                        mat.MetallicRoughnessMaterial = new Runtime.MetallicRoughnessMaterial();
                        mat.NormalTexture = new Runtime.Texture();

                        foreach (Parameter req in makeTest.requiredParameters)
                        {
                            if (req.name == ParameterName.BaseColorFactor)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorFactor = req.value;
                            }
                            else if (req.name == ParameterName.NormalTexture)
                            {
                                mat.NormalTexture.Source = req.value;
                            }
                        }

                        foreach (Parameter param in combos[comboIndex])
                        {
                            if (param.name == ParameterName.AlphaMode_Opaque ||
                                param.name == ParameterName.AlphaMode_Mask ||
                                param.name == ParameterName.AlphaMode_Blend)
                            {
                                mat.AlphaMode = param.value;
                            }
                            else if (param.name == ParameterName.AlphaCutoff)
                            {
                                mat.AlphaCutoff = param.value;
                            }
                            else if (param.name == ParameterName.DoubleSided)
                            {
                                mat.DoubleSided = param.value;
                            }
                        }
                    }

                    else if (makeTest.testArea == Tests.Material_MetallicRoughness)
                    {
                        foreach (Parameter param in combos[comboIndex])
                        {
                            if (mat.MetallicRoughnessMaterial == null)
                            {
                                mat.MetallicRoughnessMaterial = new Runtime.MetallicRoughnessMaterial();
                            }

                            if (param.name == ParameterName.BaseColorFactor)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorFactor = param.value;
                            }
                            else if (param.name == ParameterName.MetallicFactor)
                            {
                                mat.MetallicRoughnessMaterial.MetallicFactor = param.value;
                            }
                            else if (param.name == ParameterName.RoughnessFactor)
                            {
                                mat.MetallicRoughnessMaterial.RoughnessFactor = param.value;
                            }
                            else if (param.name == ParameterName.BaseColorTexture)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorTexture = new Runtime.Texture();
                                mat.MetallicRoughnessMaterial.BaseColorTexture.Source = param.value;
                            }
                            else if (param.name == ParameterName.MetallicRoughnessTexture)
                            {
                                mat.MetallicRoughnessMaterial.MetallicRoughnessTexture = new Runtime.Texture();
                                mat.MetallicRoughnessMaterial.MetallicRoughnessTexture.Source = param.value;
                            }
                        }
                    }

                    else if (makeTest.testArea == Tests.Texture_Sampler)
                    {
                        mat.MetallicRoughnessMaterial = new Runtime.MetallicRoughnessMaterial();
                        mat.MetallicRoughnessMaterial.BaseColorTexture = new Runtime.Texture();
                        mat.MetallicRoughnessMaterial.BaseColorTexture.Sampler = new Runtime.Sampler();

                        foreach (Parameter req in makeTest.requiredParameters)
                        {
                            if (req.name == ParameterName.BaseColorTexture)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorTexture.Source = req.value;
                            }
                        }

                        foreach (Parameter param in combos[comboIndex])
                        {
                            if (param.name == ParameterName.MagFilter_Nearest ||
                                param.name == ParameterName.MagFilter_Linear)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorTexture.Sampler.MagFilter = param.value;
                            }
                            else if (param.name == ParameterName.MinFilter_Nearest ||
                                     param.name == ParameterName.MinFilter_Linear ||
                                     param.name == ParameterName.MinFilter_Nearest_Mipmap_Nearest ||
                                     param.name == ParameterName.MinFilter_Linear_Mipmap_Nearest ||
                                     param.name == ParameterName.MinFilter_Nearest_Mipmap_Linear ||
                                     param.name == ParameterName.MinFilter_Linear_Mipmap_Linear)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorTexture.Sampler.MinFilter = param.value;
                            }
                            else if (param.name == ParameterName.WrapS_Clamp_To_Edge ||
                                     param.name == ParameterName.WrapS_Mirrored_Repeat ||
                                     param.name == ParameterName.WrapS_Repeat)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorTexture.Sampler.WrapS = param.value;
                            }
                            else if (param.name == ParameterName.WrapT_Clamp_To_Edge ||
                                     param.name == ParameterName.WrapT_Mirrored_Repeat ||
                                     param.name == ParameterName.WrapT_Repeat)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorTexture.Sampler.WrapT = param.value;
                            }
                        }
                    }

                    else if (makeTest.testArea == Tests.Primitive_Attribute)
                    {
                        // Clear values from the default model, so we can test those values not being set
                        wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Normals = null;

                        mat.MetallicRoughnessMaterial = new Runtime.MetallicRoughnessMaterial();
                        mat.MetallicRoughnessMaterial.BaseColorTexture = new Runtime.Texture();
                        mat.NormalTexture = new Runtime.Texture();

                        foreach (Parameter req in makeTest.requiredParameters)
                        {
                            if (req.name == ParameterName.BaseColorTexture)
                            {
                                mat.MetallicRoughnessMaterial.BaseColorTexture.Source = req.value;
                                mat.MetallicRoughnessMaterial.BaseColorTexture.TexCoordIndex = 0;
                            }
                        }

                        foreach (Parameter param in combos[comboIndex])
                        {
                            if (param.name == ParameterName.Normal)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Normals = param.value;
                            }
                            else if (param.name == ParameterName.Tangent)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Tangents = param.value;
                            }
                            else if (param.name == ParameterName.TexCoord0_Float)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordsAccessorMode =
                                    Runtime.MeshPrimitive.TextureCoordsAccessorModeEnum.FLOAT;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordSets[0] = param.value;
                            }
                            else if (param.name == ParameterName.TexCoord0_Byte)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordsAccessorMode =
                                    Runtime.MeshPrimitive.TextureCoordsAccessorModeEnum.NORMALIZED_UBYTE;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordSets[0] = param.value;
                            }
                            else if (param.name == ParameterName.TexCoord0_Short)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordsAccessorMode =
                                    Runtime.MeshPrimitive.TextureCoordsAccessorModeEnum.NORMALIZED_USHORT;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordSets[0] = param.value;
                            }
                            else if (param.name == ParameterName.TexCoord1_Float)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordsAccessorMode =
                                    Runtime.MeshPrimitive.TextureCoordsAccessorModeEnum.FLOAT;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordSets.Add(param.value);

                                var NormText = makeTest.requiredParameters.Find(e => e.name == ParameterName.NormalTexture);
                                mat.NormalTexture.Source = NormText.value;
                                mat.NormalTexture.TexCoordIndex = 1;
                            }
                            else if (param.name == ParameterName.TexCoord1_Byte)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordsAccessorMode =
                                    Runtime.MeshPrimitive.TextureCoordsAccessorModeEnum.NORMALIZED_UBYTE;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordSets.Add(param.value);

                                var NormText = makeTest.requiredParameters.Find(e => e.name == ParameterName.NormalTexture);
                                mat.NormalTexture.Source = NormText.value;
                                mat.NormalTexture.TexCoordIndex = 1;
                            }
                            else if (param.name == ParameterName.TexCoord1_Short)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordsAccessorMode =
                                    Runtime.MeshPrimitive.TextureCoordsAccessorModeEnum.NORMALIZED_USHORT;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].TextureCoordSets.Add(param.value);

                                var NormText = makeTest.requiredParameters.Find(e => e.name == ParameterName.NormalTexture);
                                mat.NormalTexture.Source = NormText.value;
                                mat.NormalTexture.TexCoordIndex = 1;
                            }
                            else if (param.name == ParameterName.Color_Vector3_Float)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].ColorAccessorMode =
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.FLOAT |
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.VEC3;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Colors = param.value;
                            }
                            else if (param.name == ParameterName.Color_Vector4_Float)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].ColorAccessorMode =
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.FLOAT |
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.VEC4;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Colors = param.value;
                            }
                            else if (param.name == ParameterName.Color_Vector3_Byte)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].ColorAccessorMode =
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.NORMALIZED_UBYTE |
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.VEC3;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Colors = param.value;
                            }
                            else if (param.name == ParameterName.Color_Vector4_Byte)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].ColorAccessorMode =
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.NORMALIZED_UBYTE |
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.VEC4;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Colors = param.value;
                            }
                            else if (param.name == ParameterName.Color_Vector3_Short)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].ColorAccessorMode =
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.NORMALIZED_USHORT |
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.VEC3;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Colors = param.value;
                            }
                            else if (param.name == ParameterName.Color_Vector4_Short)
                            {
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].ColorAccessorMode =
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.NORMALIZED_USHORT |
                                    Runtime.MeshPrimitive.ColorAccessorModeEnum.VEC4;
                                wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Colors = param.value;
                            }
                        }
                    }

                    wrapper.Scenes[0].Meshes[0].MeshPrimitives[0].Material = mat;
                    wrapper.BuildGLTF(ref gltf, geometryData);

                    if (makeTest.imageAttributes != null)
                    {
                        foreach (var image in makeTest.imageAttributes)
                        {
                            if (File.Exists(Path.Combine(imageFolder, image.Name)))
                            {
                                File.Copy(Path.Combine(imageFolder, image.Name), Path.Combine(assetFolder, image.Name), true);
                            }
                            else
                            {
                                Debug.WriteLine(imageFolder + " does not exist");
                            }
                        }
                    }

                    var assetFile = Path.Combine(assetFolder, test.ToString() + "_" + comboIndex + ".gltf");
                    glTFLoader.Interface.SaveModel(gltf, assetFile);

                    foreach (var data in dataList)
                    {
                        data.Writer.Flush();

                        var dataFile = Path.Combine(assetFolder, data.Name);
                        File.WriteAllBytes(dataFile, ((MemoryStream)data.Writer.BaseStream).ToArray());
                    }

                    mdLog.Add(new List<string> // New row for a new model
                    {
                        comboIndex.ToString() // Left column is the number of the model
                    }); 
                    int logIndex = mdLog.Count - 1;
                    List<int> nonBinaryUsed = new List<int>();
                    foreach (var possibleParam in makeTest.parameters)
                    {
                        var paramIndex = combos[comboIndex].FindIndex(e =>
                            e.name == possibleParam.name &&
                            e.prerequisite == possibleParam.prerequisite);
                        if (paramIndex != -1)
                        {
                            if (possibleParam.binarySet > 0)
                            {
                                var alreadyUsed = nonBinaryUsed.Exists(x => x == possibleParam.binarySet);
                                if (alreadyUsed)
                                {
                                    // Overwrites the empty cell if a nonbinary of the same time had already been encountered and not used
                                    mdLog[logIndex][mdLog[logIndex].Count - 1] = makeTest.ConvertValueToString(possibleParam);
                                }
                                else
                                {
                                    // Creates a new cell, since this nonbinary type had not been encountered before
                                    mdLog[logIndex].Add(makeTest.ConvertValueToString(possibleParam));
                                    nonBinaryUsed.Add(possibleParam.binarySet);
                                }
                            }
                            else
                            {
                                mdLog[logIndex].Add(makeTest.ConvertValueToString(possibleParam));
                            }
                        }
                        else
                        {
                            if (possibleParam.binarySet > 0)
                            {
                                var alreadyUsed = nonBinaryUsed.Exists(x => x == possibleParam.binarySet);
                                if (!alreadyUsed)
                                {
                                    mdLog[logIndex].Add(" ");
                                    nonBinaryUsed.Add(possibleParam.binarySet);
                                }
                            }
                            else
                            {
                                mdLog[logIndex].Add(" ");
                            }
                        }
                    }

                    var writeToLog = string.Format("{0},{1}", comboIndex, String.Join(" - ", name));
                    csv.AppendLine(writeToLog);
                }

                if (makeTest.requiredParameters != null)
                {
                    md.AppendLine(mdLogHeader[0]); // Header for the prerequisite table. Only show if the table has values.
                    foreach (var line in mdLogPrereqs)
                    {
                        md.AppendLine(String.Join(" | ", line));
                    }
                }
                else
                {
                    md.AppendLine(mdLogHeader[1]); // If there are no prerequisites, this is the header.
                }

                md.AppendLine(" "); // Linebreak
                md.AppendLine(mdLogHeader[2]); // Header for test grid table
                md.AppendLine(mdLogHeader[3]);
                foreach (var line in mdLog)
                {
                    md.AppendLine(String.Join(" | ", line));
                }
                
                var logFile = Path.Combine(assetFolder, test.ToString() + "_log.csv");
                File.WriteAllText(logFile, csv.ToString());
                var mdLogFile = Path.Combine(assetFolder, "README.md");
                File.WriteAllText(mdLogFile, md.ToString());
            }
            Console.WriteLine("Model Creation Complete!");
            Console.WriteLine("Completed in : " + TimeSpan.FromTicks(Stopwatch.GetTimestamp()).ToString());
        }
    }
}
